Re #68: Reduce the logging level of validation failures to 'debug'
jonasbn/perl-workflow pull request #103
Opened 2021-03-11 21:45 UTC by ehuelsmann

# Description

As per @oliwel's request, change the logging of the validator's "error"
to DEBUG level: it's not really an error, it's a failure of the user to
provide compliant input (which is at *most* an informational message).

At the same time, add logging of condition errors as a TRACE level
message: these are not failures by any measure; they are merely
conditions evaluating to 'false'. When debugging, it might be handy
to be able to check these, but usually this is too chatty for debugging.
Putting the logging in TRACE instead.

Addresses some of #68

## Type of change

Improvement of existing feature.

# Checklist:

- [x] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-workflow/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-19 13:43 UTC, oliwel approved these changes

2021-04-07 05:33 UTC, jonasbn requested changes
Minor phrasing issues

2021-04-07 05:33 UTC, jonasbn commented on lib/Workflow/State.pm
> +                            "state '$state'; condition '$orig_condition' failed because: $EVAL_ERROR";
Hi @ehuelsmann 

I would rephrase this to:

```suggestion
                            "state '$state'; condition '$orig_condition' failed due to: $EVAL_ERROR";
```

2021-04-07 05:33 UTC, jonasbn commented on lib/Workflow/State.pm
>                              && $self->log->debug("opposite condition '$orig_condition' failed because ' . $EVAL_ERROR");
Same as above, minor rephrasing

```suggestion
                            && $self->log->debug("opposite condition '$orig_condition' failed due to ' . $EVAL_ERROR");
```

2021-04-07 13:07 UTC, ehuelsmann commented
@jonasbn due to the fact that I incorrectly batched the last two commits, you may want to squash the changes on commit...

2021-04-08 05:33 UTC, jonasbn approved these changes
Looks good

2021-04-08 05:35 UTC, merged