Fix #113: Support action attribute to be defined as part of State config
jonasbn/perl-workflow pull request #123
Opened 2021-05-18 21:04 UTC by ehuelsmann

# Description

In the documentation for Workflow::Action, there's an explicit example
under the documentation of the C<new()> method which shows how to add
configuration (and index number) to an action class and copy that
configuration into an attribute of the Action's instance.

With this fix, that scenario is tested and has been fixed to work.

Fixes/addresses (If applicable) #113 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# Checklist:

- [x ] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-workflow/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

You might think, that this is one crazy checklist, but it is just as much written for the maintainer of the involved software :-)

2021-05-18 21:05 UTC, ehuelsmann commented
This PR deprecates (but doesn't remove) `Workflow::Factory->get_action()` and introduces `Workflow::Factory->get_action_config()`. The latter is doubtful. Maybe we should make it `_get_action_config()` instead?

2021-05-20 17:20 UTC, jonasbn requested changes
Hi @ehuelsmann 

Minor details. It looks good

2021-05-20 17:20 UTC, jonasbn commented on lib/Workflow/Factory.pm
> +        unless ($config and %$config);
Could you apply braces around the dereferencing of the reference, as recommended by [Perl::Critic::Policy::References::ProhibitDoubleSigils](https://metacpan.org/pod/Perl::Critic::Policy::References::ProhibitDoubleSigils)

```suggestion
        unless ($config and %{$config});
```

2021-05-20 17:20 UTC, jonasbn commented on lib/Workflow/State.pm
> +    my $config        = { %$common_config, %$state_config };
Could you apply braces around the dereferencing of the reference, as recommended by [Perl::Critic::Policy::References::ProhibitDoubleSigils](https://metacpan.org/pod/Perl::Critic::Policy::References::ProhibitDoubleSigils)

```suggestion
    my $config        = { %{$common_config}, %{$state_config} };
```

2021-05-20 18:11 UTC, ehuelsmann commented on lib/Workflow/Factory.pm
> +        unless ($config and %$config);
Done.

2021-05-20 18:11 UTC, ehuelsmann commented on lib/Workflow/State.pm
> +    my $config        = { %$common_config, %$state_config };
Done.

2021-05-20 18:14 UTC, merged