Document that Workflow::Validator is an interface contract
jonasbn/perl-workflow pull request #193
Opened 2022-02-18 12:27 UTC by ehuelsmann

# Description

Declaring the Workflow::Validator an interface contract as opposed to a
base class for validators allows *any* class to implement validations. This
addresses a long-standing desire of the OpenXPKI project to consolidate
the Condition and Validator concepts - in order to be able to share code
between the two - without actually consolidating them.

Closes #137

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change

This is really meant to be a documentation-only change. However, it didn't actually pan out that way, because of removing both the documentation and implementation of the `_init()` method: there's no place for a "dummy" method in an interface definition. Also, it doesn't make sense from an OOP perspective to have that method. Instead, a newly declared `init()` method should be calling its parent's `init()` as with regular OOP patterns.

# Checklist:

- [x] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-workflow/blob/master/CONTRIBUTING.md).
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

This is a good point: should we add tests which implement a validator as a blessed ref *not* derived from `Workflow::Validator` or `Workflow::Base`?
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-28 19:29 UTC, jonasbn requested changes
Looks good.

I believe we need to add `Moo` to the `cpanfile`

2022-06-28 19:50 UTC, jonasbn approved these changes
LGTM

Please ignore my previous comment, I missed it was in the documentation part

2023-07-28 21:06 UTC, ehuelsmann commented
@jonasbn As far as I'm concerned, we're ready to merge this.

2023-08-06 10:27 UTC, oliwel commented
I did not check the related code details from the general idea behind I really vote for this!

2023-08-06 11:06 UTC, merged

2023-08-06 11:06 UTC, ehuelsmann commented
Merged based on all prior approvals.